### ISSUE TITLE
Request for review: List of PR by GSoD candidates that need reviewing

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1195]
### Summary

* There are many PRs by GSoD candidates as per instructions on #1075 
* I would really love to get folks from the community involved in reviewing a few of them and help us assess the technical writing aspects of GSoD candidates

### What needs to be done?

Here is a list of PRs that need reviewing
- [x] Editing and adding content in the code quality chapter  #1186 (Done by Malvika & Camila)
- [x] New content to chapter on data licensing  #1194 
- [x] New subchapter for reviewing PRs and maintenance for GitHub collaboration #1189 
- [ ] Managing resources for remote collaboration #1176 

### Who can help?

* Anyone who has some time to review 1 of these PRs
* Please feel free to call in @malvikasharan, if you need any support

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
I can do #1189

**Comment by rosiehigman** [comment]
I can do #1194, will join you for some of the collab cafe this afternoon

**Comment by malvikasharan** [comment]
Thank you so much @sgibson91 and @rosiehigman for such a quick response! 🎉

**Comment by IIITM-Jay** [comment]
Hi @rosiehigman I too have added some contents to data licenses of which PR #1185 , I have referenced in this issue, if you have time then may I request you to please review it.

**Comment by IIITM-Jay** [comment]
Hi @rosiehigman if you have time then may I request you to please review #1185 in  which I had added contents to data Licences

**Comment by malvikasharan** [comment]
This is an outdated issue. Closing it.
