### ISSUE TITLE
Review chapter: RDM Checklist

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1298]
### Summary

Following a general review of the [Research Data Management](https://the-turing-way.netlify.app/reproducible-research/rdm.html) chapter in the [Guide for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html), there seems to be an opportunity for greater clarity and increased usability for researchers in the field. Below I outline some ideas that can be implemented in the [Checklist subchapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-resources.html). Please feel free to refute any of the suggestions, and tackle only one of the tasks (rather than all) if you want!

### What needs to be done?

- [ ] *Shorten [checklist items](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-resources.html#checklist) for focus (link to sections in book for people to find more info).*
- [ ] *Remove "Have a plan!" and add items for each of this line's suggestions.*
- [ ] *Clarify the lne on "create the data you want to see in the world" to something along the lines of "Create clear reusable data alongside helpful metadata".*
- [ ] *Share link to [DMPOnline's checklist](https://dmponline.dcc.ac.uk/files/DMP_Checklist_2013.pdf).*

### Who can help?

* *Anybody with the time to reflect on data management!*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*
