### ISSUE TITLE
Add new contributors and contributions

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1359]
### Summary

* There are many contributors and new contributions by the existing members yet to be recorded

### What needs to be done?

@all-contributors please add
- [x] @EstherPlomp for talk, blog and translation - #1355
- [x] @martinagvilas for talk, video and tutorial  for JupyterCon
- [x] @BrainonSilicon for review, idea, and maintenance #1353, #1321 and more
- [x] @Ismael-KG for review, blog and idea (several contributions)
- [x] @sgibson91 for tutorial and video for JupyterCon
- [x] @giannidsp  for bug fixing - #1350.
- [x] @paulowoicho  for idea, review and bug fixing - #1350, and more ongoing in GSoD.
- [x] @SamGuay for translation - #1342, #1343
- [x] @jessyprovencher for translation - #1339
- [x] @crangelsmith for translation and maintenance - #1337, #1338 
- [x] @camachoreina for translation - #1338
- [x] @Remi-Gau for bug report -  #1334
- [x] @skade for bug report - #1319
- [x] @StefanJanssen95 for translation - #1356
- [x] @andriannobella for translation -  #1354
- [x] @romeroclaudino for translation - #1349  
- [x] @gustavobecelli for translation - #1349
- [x] @cemulus  for translation - #1348
- [x] @varlottaang for translation - #1345
- [x] @bertinetto for translation - #1345
- [x] @lauracion for a11y - co-hosting Latin America time zone friendly coworking calls with Malvika.
- [x] @beccawilson for sharing insights with Malvika Sharan on community building, improving accessibility in the community/project and data security.
- [x] @yaseminturkyilmaz for blog and articles. 
  - contribution mentioned in [this newsletter](https://tinyletter.com/TuringWay/letters/join-collaboration-caf-today-bring-data-feminism-perspectives-to-the-turing-way-and-learn-how-we-can-promote-an-equitable-culture-in-our-community)
- [x] @Karvovskaya for blogs. 
  - contribution mentioned in [this newsletter](https://tinyletter.com/TuringWay/letters/join-collaboration-caf-today-bring-data-feminism-perspectives-to-the-turing-way-and-learn-how-we-can-promote-an-equitable-culture-in-our-community)

### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
@all-contributors please add @giannidsp for bug fixing.

**Comment by malvikasharan** [comment]
@all-contributors please add @BrainonSilicon for review, idea, and maintenance #1353, #1321 and more

**Comment by malvikasharan** [comment]
@all-contributors please add  @paulowoicho for idea, review and bug fixing - #1350, and more ongoing in GSoD.

**Comment by malvikasharan** [comment]
@Ismael-KG for review, blog and idea (several contributions).

**Comment by malvikasharan** [comment]
@all-contributors please add @Ismael-KG for review, blog, idea, and other contributions.

**Comment by malvikasharan** [comment]
@EstherPlomp for talk, blog and translation - #1355

**Comment by malvikasharan** [comment]
@all-contributors please add @EstherPlomp for talk, blog and translation - #1355

**Comment by malvikasharan** [comment]
@all-contributors please add @martinagvilas for talk, video and tutorial for JupyterCon.

**Comment by malvikasharan** [comment]
@all-contributors please add @sgibson91 for tutorial and video for JupyterCon.

**Comment by malvikasharan** [comment]
@all-contributors please add @malvikasharan for talk, maintenance, video, ProjectManagement, eventOrganizing for JupyterCon, book dash etc.

**Comment by malvikasharan** [comment]
@all-contributors please add @crangelsmith for translation and maintenance - #1337, #1338

**Comment by malvikasharan** [comment]
@all-contributors please add @SamGuay for translation - #1342, #1343

**Comment by malvikasharan** [comment]
@all-contributors please add @jessyprovencher for translation - #1339

**Comment by malvikasharan** [comment]
@all-contributors please add @camachoreina for translation - #1338

**Comment by malvikasharan** [comment]
@all-contributors please add @Remi-Gau for bug report - #1334

**Comment by malvikasharan** [comment]
@all-contributors please add @skade for bug report - #1319

**Comment by malvikasharan** [comment]
@all-contributors please add @StefanJanssen95 for translation - #1356

**Comment by malvikasharan** [comment]
@all-contributors please add @andriannobella for translation - #1354

**Comment by malvikasharan** [comment]
@all-contributors please add  @romeroclaudino for translation - #1349

**Comment by malvikasharan** [comment]
@all-contributors please add @gustavobecelli for translation - #1349

**Comment by malvikasharan** [comment]
@all-contributors please add @cemulus for translation - #1348

**Comment by malvikasharan** [comment]
@all-contributors please add @varlottaang for translatuon - #1345

**Comment by malvikasharan** [comment]
@all-contributors please add @varlottaang for translation - #1345

**Comment by malvikasharan** [comment]
@all-contributors please add @bertinetto for translation - #1345

**Comment by malvikasharan** [comment]
@all-contributors please add  @lacion for ally - co-hosting a time zone friendly coworking with Malvika

**Comment by malvikasharan** [comment]
@all-contributors please add @lauracion as a11y (co-hosting a Latin American time zone friendly coworking with Malvika)

**Comment by malvikasharan** [comment]
@all-contributors please add  @beccawilson for sharing insights with Malvika Sharan community building, improving accessibility in the community/project, and data security.

**Comment by malvikasharan** [comment]
@all-contributors please add @yaseminturkyilmaz for blog and articles.

**Comment by malvikasharan** [comment]
@all-contributors please add @Karvovskaya for blog post.
