### ISSUE TITLE
Adding Roadmap Case Study from the AutSPACEs project

### ISSUE THREAD

**Issue by lottycoupat** [alan-turing-institute/the-turing-way#1926]
### Summary

Adding a case study to the Roadmapping chapter in the Guide for Collaboration. 

### What needs to be done?

- [x] Plan writing on how the project has created/will create a Roadmap
- [x] Draft case study
- [x] Review and additional thoughts on Roadmaps
- [x] Review 
- [x] PR

### Who can help?

Anyone who wants to review writing or add extra information on Roadmapping. The current work is being drafted in this hackmd: 
[https://hackmd.io/@lottycoupat/ry65KTsd_/edit](https://hackmd.io/@lottycoupat/ry65KTsd_/edit)

**Comment by malvikasharan** [comment]
This chapter has been reviewed and published in the book. Thank you @lottycoupat for your work. <3
