### ISSUE TITLE
Turing Way/REG collaboration on UX/UI proposal

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2071]
### Summary

* This is a checklist for the collaborators to help navigate the scoping, development and execution of this project

### What needs to be done?

- [ ] Create a dedicated directory for the UX/UI, add the proposal 
- [ ] Who the stakeholders are?
  - The Turing Way team
  - REG members
  - Jupyter Book/Executable books project members 
- [ ] Describe the project charter with all stakeholders
  - [ ] Vision
  - [ ] Mission
  - [ ] Goals
  - [ ] Milestones
  - [ ] Timeline

### Who can help?

- [ ] coordinate with the REG team
- [ ] Bring an executable books team member on board
- [ ] Other Jupyter Book users who can suggest updates on #2034 

---

**Comment by malvikasharan** [comment]
Here is a related issue: https://github.com/executablebooks/jupyter-book/issues/1389

**Comment by BrainonSilicon** [comment]
Going to jump into this thread to get notifications!! I would love to help 🚀

**Comment by myyong** [comment]
@choldgraf,

> For multi-usecase books, one question I have is whether you've explore just having different books in general, or if you have a preference for one book with lots of different ways to slice and dice the chapters?

I think, if I've understood you correctly we're looking at the second option. We are aiming for a book (let's call it _the-turing-way_), which contains the superset of all chapters. We will create multiple books (eg. _the-turing-collaborator_, _the-turing-version-controller_) based on this superset.

We are looking at a profile.yaml file to allows users to edit reader-profiles, to contain a subset of pages relevant to that reader-profile. The idea is that we use the profile.yaml to auto-generate multiple tailored table of contents and folders based on superset content and superset toc.

Each time someone makes a change to _the-turing-way_ superset, the multiple books will be regenerated and redeployed.

**Comment by malvikasharan** [comment]
Meeting: 19 Nov 2021

- Onboarding Iain Stenson and Alden to the project
- Iain is already working with May and Lydia on the project
- We have 3 KPIs:
1. Two design alternatives for achieving the goals set out by project (eg. to be able to generate different books targeted to different audiences/users), evaluate and document design decisions. This KPI will also engage users to capture their experience and collect feedback before finalising the prototype.
2. A prototype for deploying books for up to 3 user groups based on design chosen in 1. This KPI will also involve community engagement to assess the impact of suggested deployment process.
3. Documentation and deployment of prototype (with feedback taken into account) as deliverable if accepted. This KPI will enable future users and contributors to tailor and deploy books developed in this project for different user groups.

**Comment by choldgraf** [comment]
A quick though on implementations here. One thing you could try is using a little bit of Javascript to hide different chapters in the left sidebar. E.g., you could use a little dictionary like:

```python
{
  "persona_a": ["page1", "page2", etc],
  "persona_b": ["page1", "page4", etc]
}
```

And then a few buttons in your sidebar or topbar where each button maps on to a user persona / use-case. Clicking a button would trigger some javascript that looks up the list of pages associated with a persona, and then hides all of the other pages.

It might get complex if you wanted a ton of specificity here, but maybe it'd be enough to hide just the top-level sections in the table of contents? Or maybe 1-2 levels deep?

**Comment by malvikasharan** [comment]
## Feedback needed: 30 Nov 2021

We need some help here. May Yong, Lydia France and Iain Stenson have created a prototype here for a student group called ‘Enrichment’ which is a Turing scheme for PhD  (still need to be populated with curated chapters): https://the-turing-way-customise.netlify.app/editions/enrichment/welcome.html
:baby_yoda_soup: Can you please provide some suggestion on naming (we would like to replace ‘edition’ with something like ‘persona’ or ‘profile’) - can you reply below with some ideas?
:art: Based on the prototype, do you have some design wishes that we can integrate?
 (once a few prototypes are in place, we will be working on providing entry way by redesigning the welcome page - we will come back for feedback on that in a week or so).

**Comment by sgibson91** [comment]
Porting my suggestion from Slack:

- `edition` -> `pathway`: Conceptually closer to what we're trying to achieve. Providing a specific persona a pathway through the resource
- `the-turing-way-customise.netlify.app` -> `the-turing-way-choose-your-own-adventure.netlify.app`: Slightly silly suggestion :laughing: https://en.wikipedia.org/wiki/Choose_Your_Own_Adventure

**Comment by malvikasharan** [comment]
I like the use of pathways for each persona. Can we instead think of combining “persona and pathway”: https://the-turing-way-persona.netlify.app/pathway/enrichment? or makes more sense when reversed https://the-turing-way-pathway.netlify.app/persona/enrichment

**Comment by sgibson91** [comment]
Is the idea that `the-turing-way-pathway.netlify.app` will provide options for multiple pathways? If yes, my only nitpick (and it is a nitpick!) would be to pluralise pathways in the URL, and then the persona is singular. Otherwise, +1

**Comment by malvikasharan** [comment]
Plural sounds good. @myyong suggested plural as well.
For the later, we can go with either 'persona' or one the synonyms that is more appropriate such as profile, group, class, user, etc.

**Comment by choldgraf** [comment]
(just a note that the netlify link above doesn't work for m!)

**Comment by malvikasharan** [comment]
Apology for not updating @choldgraf, the link has moved to the test link (which will update again soon to some semi-permanent location): https://the-turing-way-choose-your-own-adventure.netlify.app/welcome.html.

**Comment by choldgraf** [comment]
ah interesting - so you're building a new book for each pathway?

**Comment by malvikasharan** [comment]
At the  moment that seemed like one of the solutions for us. I don't see the repo that @Iain-S @LydiaFrance @myyong are working on (can you make it public: https://github.com/alan-turing-institute/bio-Turing-Way/?) - but they have gone ahead with the plan to create a separate yaml file that has list of curated chapter for each persona which then builds separate books which can be accessed through the main book.

This solution can likely be useful for the translated versions as well (pinging @camachoreina, @acocac, @BatoolMM, @AndreaSanchezTapia).

**Comment by acocac** [comment]
wowww great solution for improving users experience! also very useful for the translated versions (: @AndreaSanchezTapia @crangelsmith and I were indeed discussing today the most optimal path to deploy the translated versions in Netlify... a pending discussion with @sgibson91

**Comment by sgibson91** [comment]
I had recommended branch subdomains to @BatoolMM https://docs.netlify.com/domains-https/custom-domains/multiple-domains/#branch-subdomains, which would look something like:

- French version: `fr.the-turing-way...`
- German version: `de.the-turing-way...`
- etc...

where each translated version was hosted on a branch of the GitHub repo named with the same subdomain name (i.e., `fr` for French, `de` for German, etc).

But doing a little further reading, you would need to configure a custom domain name for the site, i.e., this wouldn't work with `the-turing-way.netlify.app` and I don't know how attached The Turing Way is to using the default domain name vs buying a domain outright.

@acocac you asked why we hadn't gone with a custom domain name in Slack, so if your plan is to do that for the Environmental AI book (sorry, I've forgotten the new name!) then I think the above link would work for you :)

**Comment by acocac** [comment]
thanks @sgibson91 for the guidance (: we'll get back to you to double check about the custom domains once we all have a decent knowledge of Crowdin, the localisation platform for translation. I'll also have a look of the link to the Environmental DS book 📚 .

**Comment by myyong** [comment]
@choldgraf (adding @Iain-S)

> ah interesting - so you're building a new book for each pathway?

We are experimenting with different solutions. In the current version, we have a single book with pathways branching off that book. So the dir structure to the phd-student pathway would look like `_build/html/pathway/phd-student/welcome.html`.

There are pros and cons, but the blocker at the moment is that we end up with one ginormous build (~20 mins build time). So yes, we are now considering the implications of having different sites/build/book for each pathway. We are checking to see: 

1. The links won't break
2. What the user experience might be like, to navigate from one book to another
3. How easy it would be to update across the different books when a change is made 
4. How easy it would be to add a new pathway

The current design with the huge build checks all the above boxes, but we think perhaps might be less scalable if Netlify has a limit on each build time, resulting in timeout errors.

**Comment by sgibson91** [comment]
IIRC @ltetrel is using multiple Jupyter Books for the NeuroLibre paper submission platform (https://www.neurolibre.org/  https://docs.neurolibre.org/). Do you have any insight into the above questions?

**Comment by ltetrel** [comment]
@myyong In our case we have one jupyter-book that takes 8 hours to build (!!). We ended up using jupyter-book caching to cache the re-execution of notebooks for our build: https://github.com/neurolibre/neurolibre-reviews/issues/6
https://github.com/NBCLab/nimare-paper
This requires user to execute and push their cache to github, so may not be ideal for scalability in your case (one repo, multiple authors), maybe you could datalad each phd-student build folder?

**Comment by ltetrel** [comment]
> I wasn't sure if I wanted to laugh or cry when I saw this:

Hahaha, we are actually debating if this submission fits our requirements.

> Does the timeout error affect your build?

So in our case, build time was never an issue, but rather notebook execution (which is really fast now with caching).

> I had to google Datalad, thank you. I'll have a look.

Basically it will help you decompose your jupyter-book build into multiple independent pieces (one piece being phd-student build):
```
for each phd-student:
    datalad get phd-student-i
    jupyter-book build
    datalad drop phd-student-i
merge all build folder
```

**Comment by myyong** [comment]
@ltetrel 

That's exactly what our code does:

```
for each phd-student:
    datalad get phd-student-i
    jupyter-book build
    datalad drop phd-student-i
merge all build folder
```

But the final build folder is large. For each piece (phd-student-i in your example) it adds about 6 mins to the build. If we reach up to i = 30, we would be looking at 180 mins for each build. And each time a contributor makes a change, we'd be rebuilding. I am wondering if we should deploy a new site for each phd-student-i, but  really, the total build time is still the same. But at least each of those builds won't be exiting with a timeout. But there are many advantages in having a single build. _goes round in circles_

Thanks for sharing your thoughts :)

**Comment by KirstieJane** [comment]
Rocking up a bit late but I like `persona` and `pathways` as discussed above ✔️ 

+1 on please make https://github.com/alan-turing-institute/bio-Turing-Way public.

**Comment by malvikasharan** [comment]
Tagging @myyong @LydiaFrance and @Iain-S for update from our last meeting as a few sentence in the comment here. 🙌

**Comment by malvikasharan** [comment]
Process for handover and conlusion of this project
1. [x] Set a handover and debrief meeting: @myyong and @malvikasharan 

Actions on REG members, @myyong, @LydiaFrance and @Iain-S, working on this project
2. [ ] Update this issue #2071 with comments summarising the progress and updates from the project for community record
3. [ ] Prepare ready to review PR (under progress #2246 ) that can be merged to The Turing Way book with at least one profile to allow community members to see and feedback on the developed UX
4. [ ] Create a new issue (connect with this issue 2071) sharing the test book which was used for creating and demo-ing the prototype
5. [ ] Provide manual/documentation for JupyterBook users who would like to use this feature in and outside The Turing Way 

Actions on me
3. [ ] Design a GSoC project that builds on this project allowing us to properly integrate the developed feature to The Turing Way and conduct community feedback
4. [ ] Create a document to share with the funders to report on the project (progress, challenges, next steps), this document should be shared on The Turing Way and JupyterBook repository by capturing all the possible solutions that we tried (with pros and cons) and reason for the chosen option in The Turing Way (this should be co-developed with REG members, especially @myyong)
