### ISSUE TITLE
Outstanding workshop actions

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#220]
### Summary

Leftover actions from today to be addressed on 21/02/2019

### What needs to be done?
- [x] Pre-workshop comms - @KirstieJane and @LouiseABowler to provide fro @rosiehigman see #222 
- [x] Workshop content and updated agendas to go into GitHub - @LouiseABowler as in #222 
- [x] Code of conduct - @KirstieJane @pherterich see #227 
- [x] evaluation/feedback form - @r-j-arnold 
- [x] hackmd for event - @KirstieJane 
- [x] Catering - @rosiehigman with @LouiseABowler and
    - [x] London
    - [x] Manchester
    - [x] Sheffield @annakrystalli 
- [ ] Networked comms/ newsletter - @pherterich #223 
- [x] stickers - PH queried with @betatim - they will be ready in March which is a bit too late for this round of workshops but maybe for the Collaborations Workshop? 
- [ ] Add aims and expectation setting to GitHub
- [ ] Cloud resources for BinderHub workshop - @KirstieJane 
- [ ] pathway to share successes - @KirstieJane 
- [ ] work through BinderHub documentation - @sgibson91 to lead
- [ ] facilitator training - @KirstieJane

**Comment by pherterich** [comment]
I'll close this as either we have addressed everything or captured it as areas for improvement in one of the feedback issues.
