### ISSUE TITLE
Newsletter - April 2022

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2330]
Creating draft newsletter for April 2022

Tentative release date: April 20

## [Tasks before release](https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html)

- [x] Collect events from past month (mid-March 2022)
- [x] Review draft on HackMD (send me an email to review [asteele@turing.ac.uk](https://github.com/alan-turing-institute/the-turing-way/pull/asteele@turing.ac.uk))
- [x] Post on Github
- [ ] Review PR
- [ ] Publish on Tiny Letter
- [ ] Promote more broadly on Twitter, Turing Slack

Tied to #2324

**Comment by Arielle-Bennett** [comment]
Can we please promote the TPS Monthly Seminar? 

Details below: 

**Wednesday 27 April 2022 | 12:30 - 14:00**

**James Muldoon (author of Platform Socialism) - Social Ownership in the Digital Economy**

_Tech companies have been criticised for their surveillance practices, privacy breaches and monopolistic ambitions. Instead of inquiring as to how we could ‘fix’ Facebook this paper explores alternatives that could replace them. It presents the idea of platform socialism - the organisation of the digital economy through the social ownership of digital assets and democratic control over the infrastructure and systems that govern our digital lives. This framework facilitates holistic thinking about the systemic nature of the problems we face and the need for genuine alternatives. To develop the principles and institutional sketch of platform socialism, I draw inspiration from the writings of two early twentieth century writers: the libertarian socialist, G. D. H. Cole and the Austrian philosopher and economist Otto Neurath. I propose new forms of participatory and decentralised governance through an ecosystem of alternative ownership models of digital platforms. How would socially-owned and controlled apps operate in transport, food delivery and short-term accommodation? Drawing from historical examples and contemporary prototypes, platform socialism examines a variety of ways communities could reclaim ownership and control over digital platforms._

Registration link: https://turing-uk.zoom.us/meeting/register/tJMtc-qtpzsqE9DB9M9x4_kpcnYN_e-bJP3d

**Comment by aleesteele** [comment]
Adding now, @Arielle-Bennett !
