### ISSUE TITLE
[WIP] Newsletter May 2022

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2331]
Creating draft newsletter for May 2022

Tentative release date: May 18

## [Tasks before release](https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html)

- [x] Collect events from past month (mid-April 2022)
- [x] Review draft on HackMD (send me an email to review [asteele@turing.ac.uk](https://github.com/alan-turing-institute/the-turing-way/pull/asteele@turing.ac.uk))
- [ ] Post on Github
- [ ] Review PR
- [ ] Publish on Tiny Letter
- [ ] Promote more broadly on Twitter, Turing Slack

**Comment by aleesteele** [comment]
https://www.emeraldgrouppublishing.com/news-and-press-releases/progress-science-depends-a-team?utm_source=twitter&utm_medium=social&utm_campaign=bnd_HiddenRefBlog_existing_20220426 - adding this  for may 2022 with @EKaroune !

**Comment by aleesteele** [comment]
- [ ] Frictionless Community call: https://frictionlessdata.io/blog/2022/05/05/april-community-call/
- [ ] Fireside chat: https://www.eventbrite.co.uk/e/enabling-inclusive-research-conferencing-in-the-post-pandemic-era-tickets-318719758377

**Comment by aleesteele** [comment]
- [ ] Ten simple rules for establishing a mentorship programme: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010015

**Comment by aleesteele** [comment]
May be for the June 2022 newsletter: [reprohack.org/event/17/](https://t.co/uiLE1m6KET)

**Comment by da5nsy** [comment]
Looks like you folks might want something from me. If so, can I get some guidance?
