### ISSUE TITLE
July newsletter

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2444]
Creating draft newsletter for July 2022

**_Feel free to post ongoing events or updates here, to be added to the newsletter_**

## [Tasks before release](https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html)

- [ ] Collect events from past month (since mid-May 2022)
- [ ] Review draft on HackMD (send me an email to review [asteele@turing.ac.uk](mailto:asteele@turing.ac.uk)
- [ ] Post on Github
- [ ] Review PR
- [ ] Publish on Tiny Letter
- [ ] Promote more broadly on Twitter, Turing Slack

## Template:
💬 : Community News
🪐 : in _The Turing Way_ orbit
📆 : Upcoming events & opportunities

**Comment by aleesteele** [comment]
📆 : https://www.eventbrite.co.uk/e/3rd-open-research-symposium-reflecting-on-the-new-open-tickets-287933315297?aff=estw&utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-source=tw&utm-term=listing
6 July

**Comment by aleesteele** [comment]
Updates from @malvikasharan re: NASA TOPs, to be included in July newsletter:

More formally, massive congratulations 
[@Sara El-Gebali](https://theturingway.slack.com/team/U016Y357HV4)
[@Yo Yehudi](https://theturingway.slack.com/team/U017F57N7DF)
[@Johanna Bayer](https://theturingway.slack.com/team/U031BRWBADC)
[@Esther Plomp](https://theturingway.slack.com/team/U016PTRFXC7)
[@Batool Almarzouq](https://theturingway.slack.com/team/U01DHA7CA58)
[@Melissa Black](https://theturingway.slack.com/team/U02GEUPQFFD)
[@Ismael Kherroubi Garcia](https://theturingway.slack.com/team/U017F57QVB3)
[@Saranjeet Kaur](https://theturingway.slack.com/team/U027N6Z9QG5)
[@Anne fouilloux](https://theturingway.slack.com/team/U03EF6BV92M)
[@Reina Camacho](https://theturingway.slack.com/team/U01FD4683RN)
[@Elio](https://theturingway.slack.com/team/U03B6FYA3K5)
 (apologies if I missed anyone), for leading and contributing as subject matter experts to the OpenCore curriculum of NASA TOPS! What a joy to see you all in the intersection of so many projects and communities. :party-blob: https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area2_Capacity_Sharing/OpenCore/OpenCore_leads.md

[OpenCore_leads.md](https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area2_Capacity_Sharing/OpenCore/OpenCore_leads.md)
TOPS Curricula Development Team
Announcements
We are pleased to announce our 2022 Transform to Open Science (TOPS) Curricula Development Team - TOPS Curricula Module Leads. We continue to receive an overwhelming number of applications and are still in the process of reviewing them until the deadline of June 15 for the role of Content Subject Matter Expert (5-7 per module).
TOPS Team / Curricula Development Team Sprints:
• June 1-3 <./events/2022-06-03-opencore-presprint-report.md|Pre-sprint>
• June 27 - July 1 (curricula sprint)
• August 9-11 (post-sptrint)
2022 TOPS Curricula Module Leads:
1. [Yo Yehudi](https://twitter.com/yoyehudi) - Ethos of Open Science
2. [Sara El-Gebali](https://twitter.com/yalahowy) - Open Data
3. [James Powell](https://www.dontusethiscode.com/), [Cameron Riddell](https://www.linkedin.com/in/cameron-riddell/) - Open Software
4. [Shilaan Alzahawi](https://shilaan.rbind.io/author/shilaan-alzahawi/) - Open Science Tools and Resources
5. [Natasha Batalha](https://natashabatalha.github.io/) - Open Results
2022 TOPS Content Subject Matter Experts (SMEs):
Deadline is June 15th. SMEs are being selected on a rolling basis. Current SME selections:
Ethos of Open Science
1. [Amber Osman](https://twitter.com/amb3r12)
2. [Miguel Silan](https://www.linkedin.com/in/miguel-silan-215482b3)
3. [Ismael Kherroubi Garcia](https://www.linkedin.com/in/ismaelkherroubi)
4. [Tomoko Bell](https://www.linkedin.com/in/tomoko-bell-49330321b)
5. [Shamsuddeen Muhammad](https://www.shmuhammad.com/)
6. [Stephen Klusza](https://twitter.com/codebiologist)
7. [Mariana Meireles](https://twitter.com/mari_meir)
Open Data
1. [Yuhan Rao](https://twitter.com/douglas_rao)
2. [Jannatul Ferdush](https://www.linkedin.com/in/jannatul-ferdush/)
3. [Siobhan Mackenzie Hall](https://twitter.com/smhall97)
4. [Hugh Shanahan](https://twitter.com/HughShanahan)
5. [Andrea Medina-Smith](https://www.linkedin.com/in/andreamedinasmith/)
6. [Esther Plomp](https://twitter.com/PhDToothFAIRy)
7. [Pauline Karega](https://www.linkedin.com/in/karega-pauline-20b72a145)
Open Software
1. [Johanna Bayer](https://twitter.com/likeajumprope)
2. [Ana Vaz](https://www.linkedin.com/in/ana-carolina-vaz-9612a814/)
3. [Sierra Kaufman](https://github.com/MillionConcepts)
4. [Taher Chegini](https://cheginit.github.io/)
5. [Yeo Keat Ee](https://www.linkedin.com/in/yeokeat/)
6. [Babatunde Onabajo](https://github.com/BabatundeOnabajo)
Open Science Tools and Resources
1. [Flavio Azevedo](https://twitter.com/Flavio_Azevedo_)
2. [Rebecca Ringuette](https://www.linkedin.com/in/rebecca-ringuette-841b0b17/)
3. [Elli Papadopoulou](https://twitter.com/elli_lib)
4. [Saranjeet Kaur Bhogal](https://saranjeetkaur.github.io/About-Me/)
5. [Tyson Swetnam](https://tysonswetnam.com/)
6. [Batool Almarzouq](https://www.linkedin.com/in/batool-almarzouq-093366a1/)
7. [Melissa Black](https://twitter.com/melissablck/)
Open Results
1. [Daniela Saderi](https://twitter.com/Neurosarda)
2. [Malvika Sharan](https://twitter.com/MalvikaSharan)
3. [Michel Lacerda](https://www.linkedin.com/in/michellacerda/)
4. [Daniel Dunleavy](https://ctbs.fsu.edu/person/daniel-j-dunleavy-phd-msw)
5. [Anne Fouilloux](https://www.linkedin.com/in/annefouilloux/)
6. [Reina Camacho Toro](https://www.linkedin.com/in/reina-camacho-toro-b3279762/)
7. [Elio Campitelli](https://eliocamp.github.io/)

**Comment by malvikasharan** [comment]
Energy Catapult identified Turing way as a comprehensive resource for the accessibility and reproducibility part of their recommendation (supplement 2): https://es.catapult.org.uk/report/data-science-from-academia-to-industry/

**Comment by malvikasharan** [comment]
Alden's talk: https://zenodo.org/record/6914444#.YuFWhPHMLb0

**Comment by aleesteele** [comment]
https://github.com/pangeo-data/foss4g-2022 - upcoming event

**Comment by HeidiSeibold** [comment]
Not sure if it's too late for the current newsletter, but it would great if it could be included in this or the next newsletter 😃 

I am starting a business that is heavily building on the content for the Turing Way book: https://heidiseibold.gitlab.io/
I offer workshops and consulting on Reproducible Data Science and on Open Science and am recommending The Turing Way to all workshop participants. 

I write about how The Turing Way is important for my work in my blog: https://heidiseibold.gitlab.io/reproducible%20research/tips/2022/08/31/recommended-reading/

---

Another update from my side: I will soon have 3 videos on the HDR UK futures platform (free training videos) about reproducible research. In each of them I mention The Turing Way as "further reading". The third video ("Introduction to  reproducible analysis pipelines") will be published in the upcoming days. The others are:

- Reproducible data analysis: a recorded webinar 
- Working towards reproducible research practices: a video lesson

![image](https://user-images.githubusercontent.com/14146757/187693819-2e348a8c-64ac-42ab-9c0a-37179eced5f7.png)

https://www.hdruk.ac.uk/careers-in-health-data-science/futures/
