### ISSUE TITLE
Review Github templates

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2447]
# Summary
Reviewing the existing Github templates (pull request & issues) for the types of tasks already used by/for/within the community

# Tasks

- [ ] Review the types of templates used on Github by The Turing Way community
- [ ] Draft pull request with sample pull requests
- [ ] Document these best practices in the Community Handbook

**Comment by da5nsy** [comment]
Relevant?: https://github.com/alan-turing-institute/the-turing-way/pull/2106

**Comment by aleesteele** [comment]
Thanks for flagging @da5nsy! Somehow missed this tag as I get all the notifications in the repo 😄

**Comment by aleesteele** [comment]
Related to #2594
