### ISSUE TITLE
Scoping build design of Turing hosted BinderHub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#246]
## Summary

This issue is to be a discussion surrounding the design of **Hub23** (the Turing hosted BinderHub instance).

There is a proposal for **3 levels** of access:

### Level 1

Any member of the _public_ is able to use minimal Azure resources to verify their own project is reproducible. For all intents and purposes, a copy of mybinder.org. See #298 

### Level 2

Any member of the _public_ is able to use Hub23 to verify _Turing_ research is reproducible (published papers or public projects) and computational Azure resources are available for those listed projects. See #297 

### Level 3

Any member of the _Turing Institute_ have the option of bringing their own Azure subscription (see #292 ). Public and private repos are supported (see #291 and #346 ). Greater computational resources are also available (see #296 ).

## What needs to be done?

- [ ] Use Azure Active Directory/GitHub for authentication of Turing Institute members (see #290 #410 )
- [ ] "Scratch" Docker/Container registry that is regularly cleaned and secure for private repos (see #293 )
- [ ] Autoscaling/restriction of Azure resources for appropriate access levels (see #300 )
- [ ] Security of access tokens/keys/passwords etc. (see #320 )
- [ ] Add any other points that are relevant or missing to this list

## Who can help?

* People with BinderHub/JupyterHub experience
* People with Azure experience
* People with Kubernetes experience

---

### Updates

**07/03/2019** - Service Principal granted by Turing IT team. Need to decide what sort of VM to deploy onto and what node count. See #306 

**07/03/2019** - Organisation Authentication working on @sgibson91 's test BinderHub. Need to do some further digging in order to convince ourselves the `read:org` scope is only allowing read only access to organisations, teams and memberships. See #290 #410

**Comment by KirstieJane** [comment]
OMG - I'm frantically working on a different project for a meeting this evening - but I LOVE the name HUB23 😆 🤣 😆 💯

**Comment by sgibson91** [comment]
Once I realised Turing + Binder = tinder, I had to come up with a better option! 🤣

**Comment by sgibson91** [comment]
Just want to log some useful links I've found pertaining to the BinderHub in case I end up shutting things down on my laptop for the workshop tomorrow.

---

* Script for auto-deploy to Google: https://github.com/nicain/binder-deploy

* Accessing private repos: https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#accessing-private-repositories

* Customising the JupyterHub deployments: https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html#customizing-your-deployment

* JupyterHub configuration reference: https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#configuration-reference

*JupyterHub optimisations: https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html#optimizations

* BinderHub docs PDF: https://media.readthedocs.org/pdf/binderhub/latest/binderhub.pdf

*Authentication: https://zero-to-jupyterhub.readthedocs.io/en/stable/authentication.html#authentication

**Comment by sgibson91** [comment]
It looks like the Azure AKS Kubernetes service only supports a single "agent pool", which can only have one type/size of VM. If/when we look at supporting different VM types (e.g. GPU and CPU) we could either:
- deploy one BinderHub per compute type on AKS
- Look at the Azure [AKS Engine](https://github.com/Azure/aks-engine), which supports multiple agen pools per Kubernetes cluster.

**Comment by betatim** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1178#issuecomment-469813124 for a discussion on "give different resources to different users". There it is in the context of a JupyterHub but once you have auth working for your BinderHub it should be quite similar.

**Comment by sgibson91** [comment]
Plan is that Hub23 will no longer be a BinderHub, but a JupyterHub instead!

- https://github.com/alan-turing-institute/hub23-deploy/issues/426
