### ISSUE TITLE
Updating the checklist section in the RDM chapter

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2476]
## Summary

The [current checklist](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-checklist.html) is not covering all the points discussed in the RDM chapter and contains some language that needs to be updated (crazy). 

### Resources

- [ ] [Borghi and van Gulick 2022](https://arxiv.org/abs/2110.00888) contains a checklist
- [ ] ?

## Who can help?

* Anyone that has RDM experience or already worked on checklists
* Anyone in need of a checklist so that they can evaluate whether the checklist is helpful.

## Updates

- [ ] Write chapter outline (WIP: https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/B1QMmFFnc)
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.
