### ISSUE TITLE
Hackathon Contribution Live Tracker

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#595]
### Summary
https://alexmorley-watch-turing-way.glitch.me is a mini-app that tracks contributions during a sprint. This issue is a place to track what needs to be done to make it re-usable.

### What needs to be done?

- [x] Link to github repo https://github.com/alexmorley/watch_turing_way
- [x] Link to edit on glitch https://glitch.com/~alexmorley-watch-turing-way
- [x] Add the remix button for the glitch page
- [x] Document which parts of the site need to be changed.

### Who can help?

- [ ] It would be really great if someone could try this out for a different repo and reply with any issues / suggestions they had! Happy to walk anyone through anything that doesn't make sense :)

---

**Comment by alexmorley** [comment]
There are two ways to make one of these for your own event:

### Quick and Easy
1. Vist https://alexmorley-watch-turing-way.glitch.me 
2. Click the fish in the top right hand corner & click Remix
4. Login to glitch (you can use github or other platforms to sign in)
5. Change the REPO_URL & TITLE variables in `routes/index.js` to match your project
5b (with a tiny bit of javascript you can take the customization much further!)
6. Click on Show at the top :) 

### Customisable and Robust
To publish online you need a publicly accessible server.
1. Clone the github repo.
2. [install npm]() if you don't have it
3. Run `npm install`
4. Change the REPO_URL & TITLE variables in `routes/index.js` to match your project
5. Run `npm start`
6. It will now be accessible at localhost:3000

**Comment by dingaaling** [comment]
Hello from 2022 @alexmorley! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!

(side note from me: this is really cool!)
