### ISSUE TITLE
[WIP, New Chapter] Software Quality Checklist

### ISSUE THREAD

**Issue by fdiblen** [alan-turing-institute/the-turing-way#878]
## Detailed description
 * The software quality checklist in NLeSC guide will be a very nice addition. https://guide.esciencecenter.nl/best_practices/checklist.html

 * This issue is a place to discuss matters relating to the writing of the chapter on **Software Quality Checklist**.
 * This chapter is being written in **PR XXX**
 * This chapter is being developed on the **checklist** branch.

## Current status

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.
