### ISSUE TITLE
Split the current research data management chapter into subsections

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#947]
### Summary
 
* The current chapter on research data management is really big and is only going to grow. 

### What needs to be done?

- [ ] Address the open PRs on rdm 
  - [x] #568 added FAIR principles and personal story from @SusannaSansone 
    - [ ] Note that related issue: https://github.com/alan-turing-institute/the-turing-way/issues/633 is still open because #568 was merged without expert review and so it would be great to have another look at the content from that PR and "fix forwards"
  - [x] #837 fixed formatting - put sentences on single lines
  - [ ] #932 makes quite a few changes to the RDM chapter - needs some work to clarify the changes
  - [ ] #904 merged but haven't been added to the book yet:
    - Currently, there is a section in rdm that briefly discusses file naming convention that can be added as one of the sub-chapters
    - see discussion here: https://github.com/alan-turing-institute/the-turing-way/issues/886
- [ ] Address open issues on rdm:
  - [ ] https://github.com/alan-turing-institute/the-turing-way/issues/798: archiving your data - add information about sharing data in a repository rather than as supplementary files
  - [ ] https://github.com/alan-turing-institute/the-turing-way/issues/315 (somewhat related)
    - @KirstieJane's opinion is that #315 is suggestion for new chapters _not_ for updates to rdm so I think we don't need to consider these suggestions for this issue (although they are interesting!) 
- [ ] Discuss to include recommendations on the contributing guideline on when someone should think about splitting a chapter
  - so far people have done that on their own.

### Who can help?

* Reviewers who can help us review the current open PRs
* Authors of these PRs and issues

**Comment by KirstieJane** [comment]
Thanks for flagging this @malvikasharan!! I've started opening up these PRs but I'm getting confused so I think I'm going to switch to pen and paper and then I'll take a picture and upload it if that's ok??

I'm hoping to have some time this week to open a big PR re-structuring the book....but this is a great mini example!

**Comment by malvikasharan** [comment]
Thanks @KirstieJane, I'd like some feedback on when we recommend that the chapter should be split up. Do you agree that it should be added in the contribution guideline? 

This issue will be a good case study to test that!

**Comment by KirstieJane** [comment]
Sure - but it's going to be hard to come up with generaliseable rules....

The angle I'd take on this would be to create better guidance on what an *editor* would do - with one of the action items be "make the book more readable by splitting up long sections into smaller ones" rather than trying to come up with how to make the decision - does that make sense?

**Comment by KirstieJane** [comment]
Is all the information on naming from the rdm chapter now contained in the new naming chapter (https://github.com/alan-turing-institute/the-turing-way/pull/904)? Or does that harmonisation need to be done?

**Comment by malvikasharan** [comment]
The harmonisation needs to be done, as the naming chapter talks about file naming in general for any project, whereas the content in rdm is about data.
