### ISSUE TITLE
[WIP] chapter: Remote and distributed collaboration

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#960]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _remote and distributed collaboration_.

## Branch for this chapter: 
- https://github.com/alan-turing-institute/the-turing-way/blob/ms-collaboration-book/book/content/remote_collaboration

### Table of contents

* Introduction
* Main aspects
* Perceived pros and cons
* Case studies for short meetings
* Case studies for conferences
* Case studies for coworking spaces
* Tool suggestions for 2020

### Resources

PR: #962

**Issues with contents to added in the chapter (check boxes when added)**
- [x] #943: Establishing protocols 
  - [ ] #940: Managing time effectively

- [ ] #938: Managing resources 
  - [ ] #939: Choices of tools   

- [ ] #942: Leadership and management   
  - [ ] #941: Accountability of the team

- [x] #965: Well being of people

- [x] #944: Pros and cons  

- [x] #861: Successful collaborations

- [ ] Case studies:

#### Checklists

- [x] Organising and running online meetings
- [x] Organising and running online events/conference/sprints
- [x] Participating in online meetings and events
- [ ] Managing a distributed team

**External resources**
- [The Carpentries handbook](https://docs.carpentries.org/)
- [Art of community](https://www.jonobacon.com/books/artofcommunity/) by Jono Bacon (ex community lead of Ubuntu)
- [Mozilla Open leaders](https://foundation.mozilla.org/en/initiatives/mozilla-open-leaders/) (and other 10 programs that came out of their last round) has been running virtual leadership training for projects that impact other communities in general.
- Rstudio resources and Greg's webinar on teaching online: https://resources.rstudio.com/upcoming-webinars/webinar-registration
- State of remote working: https://buffer.com/state-of-remote-work-2019
- Alan Turing GitHub Wiki: https://github.com/alan-turing-institute/notice-board/wiki

## Current status
This chapter is currently developing. If anyone would like to contribute they are more than welcome to do so.

 - [ ] Expand current content
 - [ ] Add their tips and tool suggestion
 - [ ] Add resources to this issue or the chapter
 - [ ] Create case studies
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to open PR (TBA)

## Updates

Content developed so far:

* Introduction
* Main aspects
* Perceived pros and cons

**Comment by malvikasharan** [comment]
Adding a CW20 hack-day Idea 8 

## Online Community Cookie Cutter (c3)

**Overview of the project**: Guiding documents/tools for leading and sustaining online research communities facilitated by collaborative projects or events.

### Participants
- Louise Bowler, Will Furnass, Colin Sauze, Malvika Sharan, Jo Leng and Mateusz Kuzak 

### Context

In Brief: Support and guidance for online communities working on open research
Researchers and research software engineers are rarely trained in community organisation. They may get involved in training and organising events, but they often will learn on the job on the go and rarely have access to support or guidance on current  (or best) practices around community organisation.

This has been a long term problem for the RSE and other communities. The response to the COVID-19 pandemic and the resulting lockdown has forced many people to work from home and developing and sustaining online communities is ever more important.
We want to use the experience and expertise from those activities ignited by COVID and document, to make it easier for future community organisers (researchers or RSEs) to start online communities.

### Problem

Much guidance and many resources exist online on how to build communities or organize events. Several are being specifically developed for online communities. However, what is sorely needed is accessible guidance to leading and sustaining online research communities that get formed organically due to online events.

As we continue to work from home due to the COVID-19 situation worldwide and suspect that this will continue for a foreseeable future, we have felt a need for such a guidance in our network. This is due to the fact that online events and projects can be organized without the need for expensive resources like venue, catering or travelling. This situation has created a unique and equitable opportunity for anyone with the internet to lead such an event, however many of us need skills to lead and sustain such online projects and people working on them.

Researchers without any prior experience with project leadership would benefit from a one-stop-shop for guidance or signposts on how to lead their projects and the resulted communities. For example, there have been some efforts to address the need for leadership/management training in the RSE/data science communities (e.g RSE Aspiring Leaders workshop). However, there isn’t yet clear guidance on these topics in general and much of this training is geared towards managing/leading within hierarchical institutional structures rather than within agile cross-institutional teams.

To effectively and inclusively lead their projects, we want help volunteer leaders to understand and deploy tasks related to onboarding members, establishing help/guide or mentoring structure for them, rewarding their contributors, offboarding ideas so that people can leave any time (specifically to avoid burnout), reviewing/enforcing Code of Conduct, sustaining infrastructure/services, ensuring data privacy and information on project governance.

### Solution

- A cookie-cutter-like tool to guide you through creating a community
  - Either a “choose your own adventure” style guide to gamify the process
  - An interactive tool (or similar) that takes you through each of the essential steps and provides the user with options and recommendations based on your preferences (like an expanded version of the “Choose a licence” website)

**And/or**

- A set of documents to capture best practice:
  - We could prepare a chapter for the Project Design section of the Turing Way: see https://deploy-preview-977--the-turing-way.netlify.com/project-design.html
  - The text for the chapter could overlap with the content for the interactive tool suggested above
a list of organisations (communities of practice) that can support new community organisers on their path

**And/or**

- Making an interactive section to the Turing Way using Jupyter Book

**Comment by malvikasharan** [comment]
CW20 hack-day Idea 5

## Remote Conferences and Collaboration: The Turing Way - CI5-CW20

### Context / Research Domain

Due to the current COVID-19 crisis, remote work has become the default mode of working for most people in research, but it has also been common practice for different people and projects before that. How can we, working remotely, maintain the communities in this mode, and make sure that the community and the people involved in it remain healthy, and productive, and have all the information and technical support they need? In open-source, this sort of remote work has been common. How can we disseminate the lessons learned in these communities to research groups and teams who are experiencing remote work, collaboration, teaching for the first time?

### Problem

People may never have worked with any of the available collaboration tools, and may not have seen the necessity of using them. Those that are new to these workflows and tools may find it hard to find and access the available resources. Nevertheless they will need to find answers to questions such as “Are the tools we choose to run our events accessible across all platforms?”, “Do we exclude, e.g., Windows users by picking a particular video conferencing tool?”, “We miss the sociability of the coffee breaks, how can we simulate them?”, ”Are there different opportunities we gain from being remote?”, “How can we counter the dangers of being in a remote event, e.g., doing multiple things at once instead of just ‘being at the conference’?”

### Solution

We describe considerations, workflows and tools for running remote activities for people that need to facilitate such an event but don’t have any previous experience. We would also like to capture things about CW20 that worked well for running future online conferences. In the course, we will describe which tools and features work well for which purpose, and other features (e.g., pricing, necessity to download, open/closed source). We also suggest solutions for more general issues, such as scheduling, and work modes suitable for online conferences (e.g., set your away message to be able to concentrate on the online event).
Outcome

A subsection of a Turing Way chapter on running collaborative online events which describes the use case of running an online event with different requirements.

**Proposed Structure:**

Activity types / Use cases (Mix and match these to build your online event!)
- workshop
- hack event
- poster session
- prototyping/ideas session
- presentations (including lightning talks)
- pre-recorded presentations
- panel sessions
- async collaboration on a text
- Tools for pair-programming
Requirements
- breakout rooms
- chat
- video/audio (where can these be tested?)
- VCS integration
- live streaming
- whiteboard
- Recording tools for pre-recorded talks
Available tools
- feature matrix
    - account needed? How can people join?
    - installation needed?
- paid-for/free
- open source
How to replicate/simulate the social aspects
- Zoom backgrounds ;)
- Virtual water cooler/coffee break
- Virtual pub quizzes
Things you wouldn’t do in person but can do virtually
- collaborative notetaking
- pre-recording talks
Scheduling (may be an issue particular to online events because people will be in their own timezones, not all in one)

**Comment by sgibson91** [comment]
@malvikasharan The checklists mentioned in the top comment, are there issues/PRs for those?
